# Generated by Django 3.2.7 on 2021-09-14 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_satisfacao', models.CharField(choices=[('B', 'Bom'), ('O', 'Ótimo'), ('R', 'Ruim')], default='O', max_length=2)),
                ('devolvido', models.BooleanField()),
                ('local_entrega', models.TextField()),
                ('comentario', models.TextField()),
                ('data_devolucao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads/% Y/% m/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Ciclista', 'Ciclista'), ('Dono', 'Dono')], max_length=10)),
                ('documento', models.CharField(max_length=11)),
                ('endereco', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(choices=[('Esportiva', 'Esportiva'), ('Passeio', 'Passeio'), ('Hibrida', 'Hibrida'), ('Outro', 'Outro')], max_length=25)),
                ('marca', models.CharField(max_length=30)),
                ('ano_fabricacao', models.DateField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.foto')),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField(auto_now=True)),
                ('comentario', models.TextField()),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bicicleta')),
                ('ciclista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.devolucao')),
            ],
        ),
    ]
